### PR TITLE
[ADD] project_purchase_usability: With this module you can access to …

### PR DESCRIPTION
**Pull request by alfredoavanzosc**
…suppliers invoices related to the project.

### CODE REVIEW

**Comment by alfredoavanzosc** [comment]
CLM7949

**Comment by alfredoavanzosc** [comment]
CLM7949

**Review by oihane — CHANGES_REQUESTED** [review]
Deberia de hacerse como migración del modulo

**Comment by oihane** [comment]
Ya existe el modulo en v16: project_purchase_link

**Pull request closed without merging**
